services:

  mysql:
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --log-bin --binlog-format=ROW  --server-id=2 --sync-binlog=1 --binlog-annotate-row-events=0 --log-bin-trust-function-creators=ON"
    volumes:
      # - "${SQL_SCRIPTS_PATH}/mysql/mosul_skip_liquibase_schema_scripts.sql:/docker-entrypoint-initdb.d/mosul_skip_liquibase_schema_scripts.sql"
      # - "${SQL_SCRIPTS_PATH}/mysql/mosul_person_attribute_type.sql:/docker-entrypoint-initdb.d/mosul_person_attribute_type.sql"
